version: "3.8"

networks:
  my-app:
    external: true

volumes:
  pgdata: {}

services:
  sobesednik:
    image: sobesednik:latest
    container_name: sobesednik
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - my-app
  postgres:
    image: postgres:10
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data:Z
    ports:
      - 5432:5432
    networks:
      - my-app
#    links:
#      - sobesednik